services:
  # --- The PostgreSQL Database ---
  db:
    image: postgres:16-alpine
    container_name: expense_postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/datad
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 3s
      timeout: 3s
      retries: 5

   # --- FastAPI App ---
  web:
    build: .
    container_name: expense_fastapi_app
    ports:
      - "8000:8000" # Maps local port 8000 on your computer to container port 8000
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      # OPTIONAL: Explicitly specify a local override here if desired
      PORT: 8000 
    volumes:
      - .:/workspace
    depends_on:
      db:
        condition: service_healthy

# --- Named Volumes---
volumes:
  postgres_data:
